export const FAMOUS_QUOTES = [
  "To be, or not to be: that is the question. (Hamlet 3 \u00b7 1)",
  "All the world\u2019s a stage, and all the men and women merely players. (As You Like It 2 \u00b7 7)",
  "Romeo, Romeo! wherefore art thou Romeo? (Romeo & Juliet 2 \u00b7 2)",
  "Now is the winter of our discontent. (Richard III 1 \u00b7 1)",
  "A horse! A horse! My kingdom for a horse! (Richard III 5 \u00b7 4)",
  "Some are born great, some achieve greatness, and some have greatness thrust upon \u2019em. (Twelfth Night 2 \u00b7 5)",
  "The lady doth protest too much, methinks. (Hamlet 3 \u00b7 2)",
  "Brevity is the soul of wit. (Hamlet 2 \u00b7 2)",
  "Parting is such sweet sorrow. (Romeo & Juliet 2 \u00b7 2)",
  "Cowards die many times before their deaths; the valiant never taste of death but once. (Julius Caesar 2 \u00b7 2)",
  "Cry \u2018Havoc!\u2019 and let slip the dogs of war. (Julius Caesar 3 \u00b7 1)",
  "Et tu, Brute? (Julius Caesar 3 \u00b7 1)",
  "If music be the food of love, play on. (Twelfth Night 1 \u00b7 1)",
  "A rose by any other name would smell as sweet. (Romeo & Juliet 2 \u00b7 2)",
  "We are such stuff as dreams are made on. (The Tempest 4 \u00b7 1)",
  "The course of true love never did run smooth. (A Midsummer Night\u2019s Dream 1 \u00b7 1)",
  "Off with his head! (Richard III 3 \u00b7 4)",
  "All that glisters is not gold. (The Merchant of Venice 2 \u00b7 7)",
  "The better part of valour is discretion. (Henry IV Pt 1 5 \u00b7 4)",
  "Uneasy lies the head that wears a crown. (Henry IV Pt 2 3 \u00b7 1)",
  "Friends, Romans, countrymen, lend me your ears. (Julius Caesar 3 \u00b7 2)",
  "This above all: to thine own self be true. (Hamlet 1 \u00b7 3)",
  "Though she be but little, she is fierce. (A Midsummer Night\u2019s Dream 3 \u00b7 2)",
  "What\u2019s past is prologue. (The Tempest 2 \u00b7 1)",
  "Lord, what fools these mortals be! (A Midsummer Night\u2019s Dream 3 \u00b7 2)",
  "The game is up. (Cymbeline 3 \u00b7 3)",
  "The world\u2019s mine oyster. (The Merry Wives of Windsor 2 \u00b7 2)",
  "Suit the action to the word, the word to the action. (Hamlet 3 \u00b7 2)",
  "I am a man more sinned against than sinning. (King Lear 3 \u00b7 2)",
  "It is a tale told by an idiot, full of sound and fury, signifying nothing. (Macbeth 5 \u00b7 5)"
];
